services:
  node:
    image: 'node:23'
    init: true
    user: 'node'
    command: 'tail -f /dev/null'
    working_dir: '/home/node'
    volumes:
      - './work_node:/home/node'
    env_file:
      - './.env'
  jdk:
    build: .
    init: true
    volumes:
      - './work_jdk:/home/work'
    env_file:
      - './.env'
  db:
    image: 'postgres:16'
    user: 'postgres'
    volumes:
      - './data_postgres:/var/lib/postgresql/data'
    env_file:
      - './.env'
  adminer:
    image: 'adminer'
    ports:
      - '49152:8080'
