/*
 * This source file was generated by the Gradle 'init' task
 */
package com.re_kid.discordbot;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class StreamNotifier {

    final static Logger logger = LoggerFactory.getLogger(StreamNotifier.class);

    public static void main(String[] args) {
        logger.info("Log Test");
    }
}
